### ISSUE TITLE
Feature-Request: Scheduled exports for backup purpose

### ISSUE THREAD

**Issue by cdanne** [brodeurlv/fastnfitness#113]
In case the phone breaks or is lost, I want to have a backup of my training log.
The "Export" feature is good enough to backup all data. After exporting the CSV files to the local storage, a file sync tool kicks in to save these files to a cloud storage or NAS.

However, I currently have to remember to take backups regularly and trigger the export manually.

It would be more convenient if:

- exports could be scheduled to happen every x days.
- alternatively: when opening the app, every x days I'm reminded a backup is due with the option to "export now" (maybe easier?).

Of course one could take this further and integrate different cloud storage services directly as target destination for the export, but for me personally the described "easier" solution would suffice.

Thanks for the great work...
Christoph

**Comment by alextsakpinis** [comment]
Once my open PR is merged, I would like to continue with that one.

My idea: since data can only change when the app is used, I would store a date holding the information about the last backup. Each time the application is opened, it is check if a given time has elapsed from the last backup. The user would then be actively asked if he wants to do a backup now. The time between two backups is selectable by the user in the settings section.

What do you think?

**Comment by brodeurlv** [comment]
Yes, that's smart and would not impact the user experience.

**Comment by cdanne** [comment]
👍 for the initiative, I still think this would make regular backups much easier. Of course there still is related #115 which would also provide an easy way for creating backups. But it looks like that is more complicated and not to be expected short term.

**Comment by alextsakpinis** [comment]
Solved by PR #199
