### ISSUE TITLE
How to build

### ISSUE THREAD

**Issue by EGUltraTM** [brodeurlv/fastnfitness#29]
Im trying to build it actually with Android Studio.

Or what was used for it?

Also which java Version is needed?

Getting this errors:

1. error: resource xml/provider_paths (aka com.easyfitness:xml/provider_paths) not found.
Message{kind=ERROR, text=error: resource xml/provider_paths (aka com.easyfitness:xml/provider_paths) not found., sources=[C:\xxx\fastnfitness-master\app\build\intermediates\manifests\full\debug\AndroidManifest.xml:74], original message=, tool name=Optional.of(AAPT)}

2. 

failed processing manifest. |  
-- | --
java.util.concurrent.ExecutionException: java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details |  
java.util.concurrent.ExecutionException: com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details |  
com.android.tools.aapt2.Aapt2Exception: AAPT2 error: check logs for details |  

@brodeurlv

**Comment by brodeurlv** [comment]
Hi EGUltraTM, 

Nice to see someone looking in detail to my project. You catch right away an issue. The reason is that I forgot to push the new files of my last update. Thank you for this, it is fixed now. You should have the provider_paths.xml now in the resource files.

Concerning your second issue, maybe it is due to the first one or maybe there is something wrong in your gradle config. You can also try a "clean project" as maybe I have pushed compile files I should not have. I messed-up some files at the beginning of my project as I forgot to config the GIT exclude file.

Let me know if it solves your problem.

And out of curiosity, what is it you would like to add to my app ?

Best regards, 

Charles

**Comment by brodeurlv** [comment]
And I forgot to answer your first question, but yes I do use Android Studio 

Android Studio 3.1.2
Build #AI-173.4720617, built on April 13, 2018
JRE: 1.8.0_152-release-1024-b02 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

Have a nice day.

**Comment by EGUltraTM** [comment]
Hi,

thanks yes the missing file fixed the project. First i would like to add the german translation to it. Then i will look into the code and can maybe help fix bugs if there are some.

A think which is missing on my side would be a kind of an calender where you can add workouts to each days of the week and then being able to start them and finish them instead of insert what you have finished :)

**Comment by brodeurlv** [comment]
Ok great ! 
I'm definitevely interrested in German translation and bug fixes :).

Concerning the calendar, I thought about it but all I have seen in every app is very heavy and not easy to use. 
I was actually more thinking about create a guided session. Example: 
1-You select an Exercise
2-You select a type of guided session (Physical maintenance, New max,...) and maybe ask some parameters
3-It creates automatically a liste of serie where either you check if you did it, else you correct it. 

However, my next priority it to create a Profile fragment, to be able to have more information (and a photo) of the user.

**Comment by brodeurlv** [comment]
I closed the issue as it is solved, but we can continue discussing future evolution of fastnfitness :).
