### ISSUE TITLE
Option to select language

### ISSUE THREAD

**Issue by sebadamus** [brodeurlv/fastnfitness#93]
Would be good to let you select the language.  I have a spanish android so the app appears in spanish.  There are some wrong translations (seems to be in portuguese), I can understand it but would be good to just be able to select the main language from options.

(if you like help to translate to spanish latinoamericano, just tell me)

Thanks

**Comment by brodeurlv** [comment]
Hi @sebadamus , 

Thank for the feedback. It weird because there are both a spanish and a protuguese-brazilian translation. From which country are you from exactly ?

Here is the spanish translation file. https://github.com/brodeurlv/fastnfitness/blob/master/app/src/main/res/values-es/strings.xml

And here is the portuguese : https://github.com/brodeurlv/fastnfitness/blob/master/app/src/main/res/values-pt-rBR/strings.xml

Can you please first confirm that it is the second file that applies by looking at the content ?
Thanks.

**Comment by brodeurlv** [comment]
Hi @sebadamus, 
Any follow-up on this ?

**Comment by brodeurlv** [comment]
No feedback. Closing issue.
